common/models/User.php
<?php

namespace common\models;

use function count;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\Url;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string  $id_user
 * @property string  $username
 * @property string  $password_hash
 * @property string  $password_reset_token
 * @property string  $verification_token
 * @property string  $email
 * @property string  $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string  $password  write-only password
 * @property string  $full_name
 *
 * @property string  $authKey
 *
 *
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED  = 0;
    const STATUS_INACTIVE = 9;
    const STATUS_ACTIVE   = 10;
    
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::class,
        ];
    }
    
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_INACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_DELETED]],
        ];
    }
    
    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id_user' => $id, 'status' => self::STATUS_ACTIVE]);
    }
    
    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
    
    /**
     * Finds user by username
     *
     * @param string $username
     *
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }
    
    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     *
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }
        
        return static::findOne([
            'password_reset_token' => $token,
            'status'               => self::STATUS_ACTIVE,
        ]);
    }
    
    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     *
     * @return static|null
     */
    public static function findByVerificationToken($token)
    {
        return static::findOne([
            'verification_token' => $token,
            'status'             => self::STATUS_INACTIVE,
        ]);
    }
    
    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     *
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        
        $timestamp = (int)substr($token, strrpos($token, '_') + 1);
        $expire    = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }
    
    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }
    
    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }
    
    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }
    
    /**
     * Validates password
     *
     * @param string $password password to validate
     *
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }
    
    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     *
     * @throws \yii\base\Exception
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
    
    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }
    
    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }
    
    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }
    
    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    
    /**
     * @return array
     */
    public static function statusLabels()
    {
        return [
            self::STATUS_ACTIVE  => self::statusLabel(self::STATUS_ACTIVE),
            self::STATUS_DELETED => self::statusLabel(self::STATUS_DELETED),
        ];
    }
    
    /**
     * @param $status
     *
     * @return null|string
     */
    public static function statusLabel($status)
    {
        switch ($status) {
            case self::STATUS_ACTIVE:
                return Yii::t('backend', 'Active');
                break;
            case self::STATUS_INACTIVE:
                return Yii::t('backend', 'Inactive');
                break;
            case self::STATUS_DELETED:
                return Yii::t('backend', 'Deleted');
                break;
            default:
                return null;
        }
    }
    
    public function getAvatar()
    {
        
        $path = Url::to('@web' . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR .
            'avatar' . DIRECTORY_SEPARATOR . $this->id_user . '.png');
        
        $filePath = Yii::$app->params['avatarUploadPath'] . DIRECTORY_SEPARATOR . $this->id_user . '.png';
        if (file_exists($filePath)) {
            
            return $path;
        }
        
        
        return Url::to('@web/img/no_profile_picture.jpg');
        
    }
    
    public function getDisplayRoles()
    {
        $roles = null;
        if (Yii::$app->authManager != null) {
            $authManager   = Yii::$app->authManager;
            $assignedRoles = $authManager->getRolesByUser($this->id_user);
            if ($assignedRoles !== null && count($assignedRoles) > 0) {
                foreach ($assignedRoles as $assignedRole) {
                    $display_text = '<span class="badge bg-blue">' . $assignedRole->name . '</span>&nbsp;';
                    $roles        .= $display_text;
                }
            }
        }
        
        return $roles;
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\form\Avatar;
use backend\models\form\PasswordResetRequest;
use backend\models\form\UserUpdate;
use backend\models\form\SignUp;
use Yii;
use common\models\User;
use backend\models\search\UserSearch;
use yii\base\UserException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('index',[
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * Displays a single User model.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view',[
            'model' => $this->findModel($id),
        ]);
    }
    
    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Signup();
        
        if ($model->load(Yii::$app->request->post()) && $user = $model->signup()) {
            return $this->redirect(['view','id' => $user->id_user]);
        }
        
        return $this->render('create',[
            'model' => $model,
        ]);
    }
    
    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = new UserUpdate();
        $user  = $this->findModel($id);
        $model->loadModel($user);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view','id' => $model->id]);
        }
        
        return $this->render('update',[
            'model' => $model,
        ]);
        
    }
    
    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }
        
        throw new NotFoundHttpException(Yii::t('backend','The requested page does not exist.'));
    }
    
    /**
     * Update a User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionChangeAvatar($id)
    {
        $model = new Avatar();
        $user  = $this->findModel($id);
        $model->loadModel($user);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view','id' => $user->id_user]);
        }else {
            return $this->render('change-avatar',[
                'model' => $model,
            ]);
        }
    }
    
    /**
     * @param $id
     *
     * @return \yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionResetPassword($id)
    {
        $model                       = $this->findModel($id);
        $passwordRequestReset        = new PasswordResetRequest();
        $passwordRequestReset->email = $model->email;
        
        if ($passwordRequestReset->sendEmail()) {
            Yii::$app->getSession()->setFlash('success',Yii::t('backend','Password reset link sent to user.'));
        }else {
            Yii::$app->getSession()->setFlash('error',Yii::t('backend','Sorry, we are unable to reset password for email provided.'));
        }
        
        
        return $this->redirect(['view','id' => $model->id_user]);
    }
    
    /**
     * @param      $id
     * @param      $id_parent
     *
     * @param null $callbackURL
     *
     * @return \yii\web\Response
     * @throws \yii\base\UserException
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionRestore($id,$id_parent = null,$callbackURL = null)
    {
        /* @var $user User */
        $user = $this->findModel($id);
        if ($user->status == User::STATUS_DELETED && Yii::$app->user->id != $user->id_user) {
            $user->status = User::STATUS_ACTIVE;
            if ($user->save()) {
                if ($callbackURL) {
                    return $this->redirect($callbackURL);
                }
                
                if ($id_parent != null) {
                    return $this->redirect(['view','id' => $id_parent]);
                }
                
                return $this->redirect(['view','id' => $id]);
            }else {
                $errors = $user->firstErrors;
                throw new UserException(reset($errors));
            }
        }
        
        return $this->redirect(['index']);
    }
    
    
    /**
     * @param      $id
     * @param      $id_parent
     *
     * @param null $callbackURL
     *
     * @return \yii\web\Response
     * @throws \yii\base\UserException
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionDelete($id,$id_parent = null,$callbackURL = null)
    {
        /* @var $user User */
        $user = $this->findModel($id);
        if ($user->status == User::STATUS_ACTIVE && Yii::$app->user->id != $user->id_user) {
            $user->status = User::STATUS_DELETED;
            if ($user->save()) {
                if ($callbackURL) {
                    return $this->redirect($callbackURL);
                }
                
                if ($id_parent != null) {
                    return $this->redirect(['view','id' => $id_parent]);
                }
                
                return $this->redirect(['view','id' => $id]);
            }else {
                $errors = $user->firstErrors;
                throw new UserException(reset($errors));
            }
        }
        
        return $this->redirect(['index']);
    }
}

backend/views/user/_form-change-avatar.php
<?php

use bupy7\cropbox\CropboxWidget;
use kartik\form\ActiveForm;
use yii\helpers\Html;

/* @var $model backend\models\form\Avatar */
?>
<div class="user-form">
    <div class="box box-primary">
        <div class="box-body">
            <?php $form = ActiveForm::begin([
                'options' => [
                    'enctype' => 'multipart/form-data',
                    'options' => ['class' => 'form'],
                ],
            ]); ?>
            
            
            <?=$form->field($model,'image_file')->widget(CropboxWidget::class,[
                'croppedDataAttribute' => 'crop_info',
            ]);?>


            <div class="form-group">
                <?=Html::submitButton('<i class="fa fa-floppy-o" aria-hidden="true"></i> ' . Yii::t('backend','Upload'),[
                    'class' => 'btn btn-primary btn-submit',
                    'title' => Yii::t('backend','Upload'),
                ])?>
                <?=Html::button(Yii::t('backend','Cancel'),['class' => 'btn btn-danger btn-back','title' => Yii::t('backend','Cancel')])?>
            </div>
            
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/user/_form-update.php
<?php

use common\models\User;
use common\widgets\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\form\UserUpdate */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">
    <div class="box box-primary">
        <div class="box-body">
            <?php $form = ActiveForm::begin(['class' => 'form']); ?>
            
            
            <?= $form->field($model, 'full_name')->textInput() ?>
            
            <?= $form->field($model, 'email')->textInput() ?>
            
            <?php echo $form->field($model, 'roles')->widget(Select2::class, [
                'data'          => ArrayHelper::map(Yii::$app->authManager->getRoles(), 'name', 'name'),
                'options'       => [
                    'multiple'    => true,
                    'placeholder' => Yii::t('backend', 'Select'),
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ])->label(Yii::t('backend', 'Roles')) ?>
            
            
            <?= $form->field($model, 'status')->dropDownList(User::statusLabels()) ?>

            <div class="panel panel-warning">
                <div class="panel-heading"><h4 class="panel-title"><?= Yii::t('backend', 'Change password') ?></h4></div>
                <div class="panel-body">
                    <?= $form->field($model, 'new_password')->passwordInput([
                        'maxlength'    => true,
                        'autocomplete' => 'new-password',
                    ]) ?>
                    
                    <?= $form->field($model, 'retype_password')->passwordInput([
                        'maxlength'    => true,
                        'autocomplete' => 'new-password',
                    ]) ?>
                </div>
            </div>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Update'), [
                    'class' => 'btn btn-primary btn-submit',
                    'title' => Yii::t('backend', 'Update'),
                ]) ?>
            </div>
            
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/user/_form.php
<?php

use common\widgets\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\User;

/* @var $this yii\web\View */
/* @var $model backend\models\form\SignUp */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <div class="box box-primary">

        <div class="box-body">
            <?php $form = ActiveForm::begin(['options' => ['class' => 'form'],]); ?>
            
            <?=$form->field($model,'username')->textInput([
                'maxlength'    => true,
                'autocomplete' => 'new-username',
            ])->label(Yii::t('backend','Username'))?>
            
            <?=$form->field($model,'full_name')->textInput()->label(Yii::t('backend','Full Name'))?>
            
            <?=$form->field($model,'email')->textInput()->label(Yii::t('backend','Email'))?>
    
            <?php echo $form->field($model,'roles')->widget(Select2::class,[
                'data'          => ArrayHelper::map(Yii::$app->authManager->getRoles(),'name','name'),
                'options'       => [
                    'multiple' => true,
                    'placeholder' => Yii::t('backend','Select'),
                ],
                'pluginOptions' => [
                    'allowClear'  => true,
                ],
            ])->label(Yii::t('backend','Roles'))?>

            
            <?=$form->field($model,'should_send_activation_mail')->checkbox(['label' => Yii::t('backend','Should Send Activation Mail')])?>
            
            <?=$form->field($model,'status')->dropDownList(User::statusLabels())->label(Yii::t('backend','Status'))?>

            <div class="form-group">
                <?=Html::submitButton(Yii::t('backend','Create'),[
                    'class' => 'btn btn-success btn-submit',
                    'title' => Yii::t('backend','Create'),
                ])?>
            </div>
            
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/user/_search.php
<?php

use common\models\User;
use common\widgets\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <?= Yii::t('app', 'Search'); ?>
        </div>
        <div class="panel-body">
            <?php $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
            ]); ?>
            <div class="row">
                <div class="col-md-3">
                    <?= $form->field($model, 'username') ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'full_name') ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'status')->widget(Select2::class,
                        [
                            'data'          => User::statusLabels(),
                            'pluginOptions' => [
                                'placeholder' => Yii::t('backend', 'Select'),
                                'allowClear'  => true,
                            ],
                        ]) ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'email') ?>
                </div>
            </div>


            <div class="form-group">
                <?= Html::submitButton('<i class="fa fa-search" aria-hidden="true"></i> ' . Yii::t('backend', 'Search'), [
                    'class' => 'btn btn-primary
                btn-search',
                    'title' => Yii::t('backend', 'Search (Alt+F)'),
                ]) ?>
                <?= Html::a('<i class="fa fa-refresh" aria-hidden="true"></i> ' . Yii::t('backend', 'Refresh'), ['index'],
                    ['class' => 'btn btn-default']) ?>
            </div>
            
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/user/change-avatar.php
<?php

/* @var $this yii\web\View */
/* @var $model backend\models\form\Avatar */

$this->title                   = Yii::t('backend', 'Change avatar');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->user->username, 'url' => ['view', 'id' => $model->user->id_user]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="user-update">
    
    <?= $this->render('_form-change-avatar', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/create.php
<?php


/* @var $this yii\web\View */
/* @var $model backend\models\form\SignUp */

$this->title                   = Yii::t('backend', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">
    
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/index.php
<?php

use common\models\User;
use common\widgets\GridView;
use kartik\grid\ActionColumn;
use kartik\grid\SerialColumn;
use mdm\admin\components\Helper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = Yii::t('backend', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">
    
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    <?php
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'panel'        => [
            'type'    => GridView::TYPE_PRIMARY,
            'heading' => '<i class="glyphicon glyphicon-list"></i> ' . $this->title,
        ],
        'toolbar'      => [
            'content' =>
                Helper::checkRoute('user/create') ?
                    Html::a('<i class="fa fa-plus" aria-hidden="true"></i>', ['create'], ['class' => 'btn btn-success btn-sm']) : '',
        ],
        'columns'      => [
            
            ['class' => SerialColumn::class],
            'username',
            'full_name',
            'email:email',
            'created_at:date',
            [
                'attribute' => 'status',
                'value'     => function ($model) {
                    return $model->status == User::STATUS_ACTIVE ? '<span class="badge bg-green">' . User::statusLabel($model->status) . '</span>' : '<span class="badge bg-red">' . User::statusLabel($model->status) . '</span>';
                },
                'format'    => 'raw',
            ],
            [
                'class'    => ActionColumn::class,
                'template' => Helper::filterActionColumn(['view', 'update', 'restore', 'delete']),
                'buttons'  => [
                    'restore' => function ($url, $model) {
                        if ($model->status == User::STATUS_ACTIVE || Yii::$app->user->id == $model->id_user) {
                            return '';
                        }
                        $options = [
                            'title'        => Yii::t('backend', 'Restore'),
                            'aria-label'   => Yii::t('backend', 'Restore'),
                            'data-confirm' => Yii::t('backend', 'Are you sure you want to restore this item?'),
                            'data-method'  => 'post',
                            'data-pjax'    => '0',
                        ];
                        
                        return Html::a('<span class="glyphicon glyphicon-ok text-success"></span>', [
                            '/user/restore',
                            'id'          => $model->id_user,
                            'callbackURL' => Yii::$app->request->url,
                        ], $options);
                    },
                    'delete'  => function ($url, $model) {
                        if ($model->status == User::STATUS_DELETED || Yii::$app->user->id == $model->id_user) {
                            return '';
                        }
                        $options = [
                            'title'        => Yii::t('backend', 'Delete'),
                            'aria-label'   => Yii::t('backend', 'Delete'),
                            'data-confirm' => Yii::t('backend', 'Are you sure you want to delete this item?'),
                            'data-method'  => 'post',
                            'data-pjax'    => '0',
                        ];
                        
                        return Html::a('<span class="glyphicon glyphicon-remove text-danger"></span>', [
                            '/user/delete',
                            'id'          => $model->id_user,
                            'callbackURL' => Yii::$app->request->url,
                        ], $options);
                    },
                    
                    'update' => function ($url, $model) {
                        if (Yii::$app->user->id == $model->id_user) {
                            return '';
                        }
                        $options = [
                            'title'      => Yii::t('backend', 'Update'),
                            'aria-label' => Yii::t('backend', 'Update'),
                        ];
                        
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['/user/update', 'id' => $model->id_user],
                            $options);
                    },
                ],
            ],
        ],
    ]);
    ?>
</div>

backend/views/user/update.php
<?php

/* @var $this yii\web\View */
/* @var $model \backend\models\form\UserUpdate */

$this->title                   = Yii::t('backend', 'Update User: ' . $model->user->id_user, [
    'nameAttribute' => '' . $model->user->id_user,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->user->id_user, 'url' => ['view', 'id' => $model->user->id_user]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="user-update">
    
    <?= $this->render('_form-update', [
        'model' => $model,
    ]) ?>

</div>